name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
          description: log level
          required: true
          type: choice
          options:
            - info
            - warning
            - debug
          default: info
      environment:
        type: environment
      input:
        type: string
        required: true

jobs:
  
  log-the-inputs:
    strategy:
      matrix: fromJSON(${{ inputs.input}})
      

    runs-on: ${{ matrix.os }}
    steps:
       -  run: |
            echo "Log level: $LEVEL"
            echo "Tags: $TAGS"
            echo "Environment: $ENVIRONMENT"
            echo "Version: ${{ matrix.version }}"
          env:
            LEVEL: ${{ inputs.logLevel }}
            TAGS: ${{ inputs.tags }}
            ENVIRONMENT: ${{ inputs.environment }}
