# This is a basic workflow to help you get started with Actions

name: Secrets



# Controls when the workflow will run
on:
  workflow_dispatch:
env:
  cat_name: "Puszek"
  WORKFLOW_VAR: "Hello from workflow"

jobs:
  display-variables:
    name: ${{ vars.ENVIRONMENT_VAR }}
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Hello from job #0"
    steps:
    - name: Use variables 1
      env:
        STEP_VAR: "Hello from step #0"
      run: |
        echo "Repository variable : ${{ vars.REPOSITORY_VAR }}"
        echo "Organization variable : ${{ vars.ORGANIZATION_VAR}}"
        echo "Environment variable : ${{vars.ENVIRONMENT_VAR}}"
        echo "Ala ma kota o nazwie ${{ env.cat_name }}"
        echo "Powinna być zmienna w scopie workflow:$WORKFLOW_VAR"
        echo "Powinna być zmienna w scopie joba:$JOB_VAR"
        echo "Powinna być zmienna w scopie stepu:$STEP_VAR"
    
    - name: Use variables 1
      env:
        STEP_VAR: "Hello from step #1"
      run: |
        echo "Ala ma kota o nazwie <WYPISZ TU IMIĘ KOTA ZAPISANE W ZMIENNEJ
        cat_name>"
        echo "Powinna być zmienna w scopie workflow:$WORKFLOW_VAR"
        echo "Powinna być zmienna w scopie joba:$JOB_VAR"
        echo "NIE powinna być zmienna w scopie stepu:$STEP_VAR"

  display-variables2:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Hello from job #1"
    steps:
    - name: Use variables in display-variables2
      env:
        STEP_VAR: "Hello from step #1"
      run: |
        echo "Powinna być zmienna w scopie workflow:$WORKFLOW_VAR"
        echo "NIE powinna być zmienna w scopie joba:$JOB_VAR"
        echo "NIE powinna być zmienna w scopie stepu:$STEP_VAR"
 
